---
title: "acs_plots"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(baltimorecensus)
library(tidyverse)
library(forcats)
library(pilot)
library(stringr)
```

```{r}
xwalk_blocks <- baltimorecensus::baltimore_blocks %>%
  dplyr::left_join(
    sf::st_drop_geometry(baltimorecensus::baltimore_tracts),
    by = c("tractce20" = "tractce")
  ) %>%
  dplyr::select(
    block = geoid20,
    tract = geoid,
    block_name = name20,
    tract_name = namelsad,
    housing20,
    pop20
  )

inspire_plans_exp <-
  mapbaltimore::inspire_plans |>
  dplyr::filter(plan_name_short != "Bay Brook EMS") |>
  sfext::st_buffer_ext(dist = 0.25, unit = "mi") |>
  dplyr::bind_rows(
    mapbaltimore::inspire_plans |>
      dplyr::filter(plan_name_short == "Bay Brook EMS")
  ) |> 
  dplyr::select(name = plan_name_short)

baltimore_city_inspire_mask <-
  sfext::st_erase(
  mapbaltimore::baltimore_city,
  inspire_plans_exp
  )

xwalk_inspire_exp <-
  xwalk_blocks |>
  dplyr::select(block, tract, housing20, pop20) %>%
  sf::st_transform(2804) %>%
  sf::st_join(inspire_plans_exp |>
                dplyr::bind_rows(
                  sfext::st_erase(mapbaltimore::baltimore_city, inspire_plans_exp)
                ),
              left = FALSE, largest = TRUE) %>%
  dplyr::filter(housing20 > 0) %>%
  sf::st_set_geometry(NULL) %>%
  dplyr::group_by(tract, name) %>%
  dplyr::summarise(
    pop20 = sum(pop20, na.rm = TRUE),
    housing20 = sum(housing20, na.rm = TRUE)
  ) %>%
  dplyr::mutate(
    weight_pop20 = round(pop20 / sum(pop20, na.rm = TRUE), digits = 2),
    weight_housing20 = round(housing20 / sum(housing20, na.rm = TRUE), digits = 2)
  ) %>%
  dplyr::ungroup() %>%
  dplyr::select(name, tract, weight_pop20, weight_housing20) |>
  dplyr::filter(name != "Baltimore city")

xwalk_inspire <-
  xwalk_blocks |>
  dplyr::select(block, tract, housing20, pop20) %>%
  sf::st_transform(2804) %>%
  sf::st_join(mapbaltimore::inspire_plans |>
                dplyr::select(name = plan_name_short) |>
                dplyr::bind_rows(
                  sfext::st_erase(mapbaltimore::baltimore_city, mapbaltimore::inspire_plans)
                ),
              left = FALSE, largest = TRUE) %>%
  dplyr::filter(housing20 > 0) %>%
  sf::st_set_geometry(NULL) %>%
  dplyr::group_by(tract, name) %>%
  dplyr::summarise(
    pop20 = sum(pop20, na.rm = TRUE),
    housing20 = sum(housing20, na.rm = TRUE)
  ) %>%
  dplyr::mutate(
    weight_pop20 = round(pop20 / sum(pop20, na.rm = TRUE), digits = 2),
    weight_housing20 = round(housing20 / sum(housing20, na.rm = TRUE), digits = 2)
  ) %>%
  dplyr::ungroup() %>%
  dplyr::select(name, tract, weight_pop20, weight_housing20) |>
  dplyr::filter(name != "Baltimore city")

census_table_metadata <-
  load_census_reporter_metadata(year = 2021)

census_column_metadata <-
  load_census_reporter_metadata(year = 2021, metadata = "column")

# Get Census data ----

table_vars <-
  c(
    "B08201",
    "B08105A",
    "B08105B",
    "B08119",
    "B08130",
    "B08134",
    "B08137",
    "B08406",
    "B08603",
    "B08141",
    "B08534",
    "B08536",
    "B01003", # total pop
    "B01001", # sex by age
    "B03002", # race
    "B05001", # foreign_born
    # Employment Status
    "B23025",
    # tenure
    "B25003",
    # year moved in by tenure
    "B25038",
    # housing_cost
    "B25106",
    # housing cost as share of household income
    "B25070",
    # vehicles
    "B08201",
    # education
    "B06009",
    # median_income
    "B19013",
    # median income by race
    "B19013A", "B19013B", "B19013C", "B19013D", "B19013E", "B19013F", "B19013G", "B19013H", "B19013I",
    # Household income
    "B19001",
    # poverty
    "C17002",
    # pov_age
    "B17024",
    # Tenure by household type and preserve/age of own children
    "B25115",
    # Language Spoken at Home for the Population 5 Years and Over
    "C16001",
    # Households by Presence of People 65 Years and Over, Household Size and Household Type
    "B11007",
    # Other housing vars
    "B07013",
    # Sex by Age by Ambulatory Difficulty
    # "C18105",
    # School Enrollment by Level of School
    "B14001",
    # Educational Attainment
    "B15003",
    # Sex by Occupation for the Civilian Employed Population 16 Years and Over
    "C24010",
    "B25074", "B25014", "B05002", "B25015",
    "B25014A", "B25014B", "B25014I", "B28008", "B14001", "B08012",
    "B25003A", "B25003B", "B25003I"
  ) %>%
  unique()


# select_counties <- c("Baltimore city, Maryland", "Baltimore County, Maryland", "Anne Arundel County, Maryland")

county_acs <- purrr::map_dfr(
  table_vars,
  ~ tidycensus::get_acs(
    geography = "county",
    table = .x,
    state = select_state,
    year = 2021,
    survey = "acs5",
    cache = TRUE,
    key = "91c1e586033430549708bd6c8d9a5695b9d50205"
  )
)

county_acs_labelled <- county_acs %>%
  janitor::clean_names("snake") %>%
  mutate(
    geography = "County"
  ) %>%
  label_acs()


readr::write_rds(county_acs_labelled, "maryland_counties_acs2021_acs5yr.rda")


msa_acs <- purrr::map_dfr(
  table_vars,
  ~ tidycensus::get_acs(
    geography = "metropolitan/micropolitan statistical area",
    table = .x,
    year = 2021,
    survey = "acs5",
    cache = TRUE
  )
)

msa_acs_labelled <- msa_acs %>%
  janitor::clean_names("snake") %>%
  mutate(
    geography = "Metro area"
  ) %>%
  label_acs()

readr::write_rds(msa_acs_labelled, "msa_acs2021_acs5yr.rda")


tract_acs <- purrr::map_dfr(
  table_vars,
  ~ tidycensus::get_acs(
    geography = "tract",
    table = .x,
    county = "Baltimore city",
    state = select_state,
    year = 2021,
    survey = "acs5",
    cache = TRUE
  )
)

tract_acs_labelled <- tract_acs %>%
  janitor::clean_names("snake") %>%
  mutate(
    geography = "Tract"
  ) %>%
  label_acs()

readr::write_rds(tract_acs_labelled, "baltimorecity_tract_acs2021_acs5yr.rda")

inspire_acs <-
  xwalk_inspire %>%
  dplyr::rename(
    geoid = tract
  ) |>
  dplyr::left_join(select(tract_acs_labelled, -name), by = "geoid") %>%
  dplyr::group_by(variable, name) %>%
  dplyr::summarise(
    estimate = round(sum(estimate * weight_housing20)),
    moe = round(tidycensus::moe_sum(moe, estimate * weight_housing20))
  ) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(
    geography = "INSPIRE Area"
  ) %>%
  label_acs(perc = FALSE) %>%
  calc_perc("name")

inspire_exp_acs <-
  xwalk_inspire_exp %>%
  dplyr::rename(
    geoid = tract
  ) |>
  dplyr::left_join(select(tract_acs_labelled, -name), by = "geoid") %>%
  dplyr::group_by(variable, name) %>%
  dplyr::summarise(
    estimate = round(sum(estimate * weight_housing20)),
    moe = round(tidycensus::moe_sum(moe, estimate * weight_housing20))
  ) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(
    geography = "INSPIRE Area (Expanded)"
  ) %>%
  label_acs(perc = FALSE) %>%
  calc_perc("name")

inspire_exp_acs$name <- paste0(inspire_exp_acs$name, " (Expanded)")

readr::write_rds(inspire_exp_acs, "inspire_exp_acs2021_acs5yr.rda")
```


```{r}
county_acs_labelled <- readr::read_rds("maryland_counties_acs2021_acs5yr.rda")
msa_acs_labelled <- readr::read_rds("msa_acs2021_acs5yr.rda")
tract_acs_labelled <- readr::read_rds("baltimorecity_tract_acs2021_acs5yr.rda")
inspire_acs <- readr::read_rds("inspire_acs2021_acs5yr.rda")
inspire_exp_acs <- readr::read_rds("inspire_exp_acs2021_acs5yr.rda")
```


```{r}
combine_acs <- inspire_acs %>%
  bind_rows(inspire_exp_acs) |>
  filter(name %in% c(select_area)) |>
  bind_rows(county_acs_labelled |>
             filter(name %in% select_counties)
            ) %>%
  bind_rows(msa_acs_labelled |>
              filter(name %in% select_msa)) %>%
  relocate(table_title, column_title, .after = variable)

## Recoding
combine_acs$name <- as.character(combine_acs$name)
combine_acs$name <-
  forcats::fct_recode(combine_acs$name,
                      # "Baltimore Highlands" = "Baltimore Highlands", # NOTE: This is hardcoded
                      "John Ruhrah EMS Area" = "John Ruhrah EMS (Expanded)",
                      "Baltimore City" = "Baltimore city, Maryland",
                      "Baltimore MSA" = "Baltimore-Columbia-Towson, MD Metro Area"
  )

combine_acs$name <- forcats::fct_inorder(combine_acs$name)

combine_acs %>%
  pull_table(table = "B25003") %>%
  filter(perc_estimate < 1) %>%
  ggplot() +
  aes(x = perc_estimate, y = column_title, fill = column_title) +
  geom_col(color = NA) +
  # scale_fill_brewer(palette = "Dark2") +
  scale_x_continuous(labels = scales::label_percent()) +
  geom_errorbarh(aes(xmin = perc_estimate - moe_perc, xmax = perc_estimate + moe_perc),
                 size = 0.35, height = 0.35) +
  labs(
    y = "Tenure",
    x = "Percent of  occupied units"
  ) +
  guides(fill = "none") +
  facet_wrap(~name, ncol = 1) +
  plot_theme() +
  pilot::scale_fill_pilot()


race_data <- combine_acs %>%
  pull_table(table = "B03002", vars = c("B03002_003", "B03002_004", "B03002_012")) %>%
  mutate(
    column_title = fct_recode(
      column_title,
      "White" = "White alone",
      "Black" = "Black or African American alone",
      "Latino" = "Hispanic or Latino:"
    ),
    column_title = fct_relevel(column_title, c("Latino", "White", "Black"))
  )

race_data %>%
  ggplot() +
  aes(x = perc_estimate, y = column_title, fill = column_title) +
  geom_col(color = NA) +
  geom_errorbarh(aes(xmin = perc_estimate - moe_perc, xmax = perc_estimate + moe_perc), size = 0.35, height = 0.35) +
  # scale_fill_brewer(palette = "Dark2") +
  scale_x_continuous(labels = scales::label_percent()) +
  labs(
    y = "Race/ethnicity",
    x = "Percent of total population"
  ) +
  guides(fill = "none") +
  facet_wrap(~ name, ncol = 1) +
  plot_theme() +
  scale_fill_pilot(palette = "seven")


race_data |>
  gt::gt()

recoded_mode_share <- combine_acs |>
  filter(
    #  table_id %in% c("B08406"),
    variable %in% c("B08137_004", "B08137_007", "B08137_010", "B08137_016", "B08137_013", "B08137_019")  #!is.na(parent_column_id)
  ) |>
  # View()
  mutate(
    column_title = factor(column_title) |>
      fct_inorder(),
    column_title = str_remove(column_title, ":$"),
    column_title = case_when(
      column_title == "Car, truck, or van - drove alone" ~ "Drove alone",
      column_title == "Car, truck, or van - carpooled" ~ "Carpooled",
      column_title == "Public transportation (excluding taxicab)" ~ "Public transit",
      column_title == "Walked" ~ "Walked",
      column_title == "Taxicab, motorcycle, bicycle, or other means" ~ "Taxi, bike, or other",
      column_title ==  "Worked from home" ~ "Worked from home"
    )
  )

recoded_mode_share |>
  ggplot() +
  geom_col(aes(x = name, y = perc_estimate, fill = column_title), position = "stack", alpha = 0.85) +
  #facet_wrap(~ geography) #, scales = "free_y") +
  coord_flip() +
  pilot::scale_fill_pilot() +
  # scale_fill_brewer(palette = "Dark2") +
  scale_y_continuous(labels = scales::label_percent()) +
  labs(
    x = "",
    y = "Share of total workers",
    fill = "Mode of transportation"
  ) +
  plot_theme() +
  theme(legend.position = "bottom",
        legend.justification = c("right", "bottom")
  )

recoded_mode_share |>
  gt::gt()



recoded_housing_cost_income <-
  combine_acs |>
  pull_table(table = "B25106") |>
  mutate(
    column_title = str_remove(column_title, ":$"),
    tenure = if_else(str_detect(column_title, "Owner-occupied housing units|Renter-occupied housing units"), column_title, ""),
    income = if_else(str_detect(column_title, "\\$"), column_title, ""),
    cost_burdened = if_else(str_detect(column_title, "30 percent or more"), "Housing cost burden", "No housing cost burden"),
    .after = column_title
  ) |>
  naniar::replace_with_na(list(tenure = "", income = "")) |>
  tidyr::fill(tenure, income, .direction = "down") |>
  mutate(
    income = fct_inorder(income)
  )


recoded_housing_cost_income |>
  filter(indent == 3) |>
  mutate(
    income = str_replace_all(income, ",000|(,999$)", "K"),
    income = fct_inorder(income)
  ) |>
  group_by(
    name, income, cost_burdened
  ) |>
  summarise(
    total_est = sum(estimate, na.rm = TRUE),
    total_perc = sum(perc_estimate)
  ) |>
  gt::gt()
  # ggplot() +
  # geom_col(aes(x = total_perc, y = income, fill = cost_burdened), alpha = 0.8) +
  # facet_wrap(~ name) +
  # scale_x_continuous(labels = scales::label_percent()) +
  # plot_theme() +
  # pilot::scale_fill_pilot() +
  # theme(
  #   legend.position = "bottom",
  #   legend.justification = c("right", "bottom")
  # ) +
  # labs(
  #   y = "Household income",
  #   x = "Share of total households",
  #   fill = "Category"
  # )



library(dplyr)
library(purrr)
library(stringr)
library(ggplot2)
library(mapbaltimore)
library(pilot)
library(gt)
library(forcats)



plot_theme <- function(axis_title_size = 11,
                       axis_text_size = 12,
                       theme_text_family = "Atkinson Hyperlegible",  #"Helvetica",
                       ...) {
  list(
    pilot::theme_pilot(
      title_family = theme_text_family,
      subtitle_family = theme_text_family,
      axis_title_family = theme_text_family,
      axis_text_family = theme_text_family,
      legend_title_family = theme_text_family,
      legend_text_family = theme_text_family,
      facet_title_family = theme_text_family,
      caption_family = theme_text_family,
      axis_title_size = axis_title_size,
      axis_text_size = axis_text_size,
      ...
    ),
    theme(
      legend.background = element_blank()
    )
  )
}

add_tract_geometry <- function(x) {
  x %>%
    left_join(mapbaltimore::baltimore_tracts, by = "geoid") %>%
    sf::st_as_sf()
}


simple_money_table <- function(x) {
  table_title <- unique(x$table_title)

  multi_column <- length(unique(x$column_title)) > 1

  if (multi_column) {
    x <- x %>%
      select(name, column_title, estimate, moe)
  } else {
    x <- x %>%
      select(name, estimate, moe)
  }

  x %>%
    group_by(name) %>%
    gt() %>%
    tab_header(
      title = table_title
    )
}

pull_table <- function(x, meta = FALSE, table = NULL, drop_vars = NULL, column = NULL, vars = NULL, geography = NULL) {
  x <- x %>%
    dplyr::filter(table_id %in% table)

  if (meta) {
    return(x)
  }

  if (!is.null(drop_vars)) {
    x <- x %>%
      filter(!(variable %in% drop_vars))
  }


  if (!is.null(vars)) {
    x <- x %>%
      filter(variable %in% vars)
  }

  if (!is.null(column)) {
    x <- x %>%
      filter(column_title %in% column)
  }

  if (!is.null(geography)) {
    x <- x %>%
      filter(geography %in% geography)
  }

  x
}


combine_acs %>%
  pull_table(table = "B25003") %>%
  filter(perc_estimate < 1) %>%
  ggplot() +
  aes(x = perc_estimate, y = column_title, fill = column_title) +
  geom_col(color = NA) +
  # scale_fill_brewer(palette = "Dark2") +
  scale_x_continuous(labels = scales::label_percent()) +
  geom_errorbarh(aes(xmin = perc_estimate - moe_perc, xmax = perc_estimate + moe_perc), size = 0.35, height = 0.35) +
  labs(
    y = "Tenure",
    x = "Percent of  occupied units"
  ) +
  guides(fill = "none") +
  facet_wrap(~name, ncol = 1) +
  plot_theme() +
  plot_fill_scale()

papersize::ggsave_ext(
  filename = glue::glue("{janitor::make_clean_names(area_label)}_tenure_plot.pdf"),
  fileext = "pdf",
#  device = cairo_pdf,
  width = 6, height = 6
)


combine_acs %>%
  pull_table(table = "B05002") %>%
  filter(
    variable %in% c("B05002_003", "B05002_004", "B05002_014", "B05002_021", "B05002_026"),
    name != "Baltimore MSA") %>%
  select(name, column_title, perc_estimate, moe_perc) %>%
  mutate(
    column_title = case_when(
      column_title == "Born in state of residence" ~ "Native (born in MD)",
      column_title == "Born in other state in the United States:" ~ "Native (born elsewhere in US)",
      column_title == "Naturalized U.S. citizen" ~ "Naturalized citizen (all)",
      column_title == "Not a U.S. citizen" ~ "Non-citizen (all)",
      column_title == "Latin America" ~ "Non-citizen (born in Latin America)"
    ),
    column_title = forcats::fct_inorder(column_title),
    column_title = forcats::fct_rev(column_title)
  ) %>%
  ggplot() +
  aes(x = perc_estimate, y = column_title, fill = column_title) +
  geom_col(color = NA) +
  geom_errorbarh(aes(xmin = perc_estimate - moe_perc, xmax = perc_estimate + moe_perc), size = 0.35, height = 0.35) +
  # scale_fill_brewer(palette = "Dark2") +
  scale_x_continuous(labels = scales::label_percent()) +
  labs(
    y = "Category",
    x = "Share of total population"
  ) +
  guides(fill = "none") +
  facet_wrap(~name, ncol = 1) +
  plot_theme() +
  scale_fill_pilot(palette = "seven")


papersize::ggsave_ext(
  filename = glue::glue("{janitor::make_clean_names(params$area_label)}_birthplace_plot.pdf"),
  device = cairo_pdf,
  width = 8, height = 6
)


race_acs_data <- combine_acs %>%
  pull_table(table = "B03002", vars = c("B03002_003", "B03002_004", "B03002_012")) %>%
  mutate(
    column_title = fct_recode(
      column_title,
      "White" = "White alone",
      "Black" = "Black or African American alone",
      "Latino" = "Hispanic or Latino:"
    ),
    column_title = fct_relevel(column_title, c("Latino", "White", "Black"))
  )

race_acs_data %>%
  ggplot() +
  aes(x = perc_estimate, y = column_title, fill = column_title) +
  geom_col(color = NA) +
  geom_errorbarh(aes(xmin = perc_estimate - moe_perc, xmax = perc_estimate + moe_perc), size = 0.35, height = 0.35) +
  # scale_fill_brewer(palette = "Dark2") +
  scale_x_continuous(labels = scales::label_percent()) +
  labs(
    y = "Race/ethnicity",
    x = "Percent of total population"
  ) +
  guides(fill = "none") +
  facet_wrap(~name, ncol = 1) +
  plot_theme() +
  scale_fill_pilot(palette = "seven")

race_acs_data %>%
  make_acs_tbl()

ggsave(
  filename = glue::glue("{janitor::make_clean_names(params$area_label)}_race_plot.pdf"),
  device = cairo_pdf,
  width = 6, height = 6
)

commute_acs_data <- combine_acs |>
  filter(
    #  table_id %in% c("B08406"),
    variable %in% c("B08137_004", "B08137_007", "B08137_010", "B08137_016", "B08137_013", "B08137_019") # !is.na(parent_column_id)
  ) |>
  # View()
  mutate(
    column_title = factor(column_title) |>
      fct_inorder(),
    column_title = str_remove(column_title, ":$"),
    column_title = case_when(
      column_title == "Car, truck, or van - drove alone" ~ "Drove alone",
      column_title == "Car, truck, or van - carpooled" ~ "Carpooled",
      column_title == "Public transportation (excluding taxicab)" ~ "Public transit",
      column_title == "Walked" ~ "Walked",
      column_title == "Taxicab, motorcycle, bicycle, or other means" ~ "Taxi, bike, or other",
      column_title == "Worked from home" ~ "Worked from home"
    )
  )

commute_acs_data |>
  ggplot() +
  geom_col(aes(x = name, y = perc_estimate, fill = column_title), position = "stack", alpha = 0.85) +
  # facet_wrap(~ geography) #, scales = "free_y") +
  coord_flip() +
  pilot::scale_fill_pilot() +
  # scale_fill_brewer(palette = "Dark2") +
  scale_y_continuous(labels = scales::label_percent()) +
  labs(
    x = "",
    y = "Share of total workers",
    fill = "Mode of transportation"
  ) +
  plot_theme() +
  theme(
    legend.position = "bottom",
    legend.justification = c("right", "bottom")
  )

ggsave(
  filename = glue::glue("{janitor::make_clean_names(params$area_label)}_commute_mode_plot.pdf"),
  device = cairo_pdf,
  width = 8.5, height = 6
)

commute_acs_data %>%
  make_acs_tbl()

recoded_housing_cost_income <-
  combine_acs |>
  pull_table(table = "B25106") |>
  mutate(
    column_title = str_remove(column_title, ":$"),
    tenure = if_else(str_detect(column_title, "Owner-occupied housing units|Renter-occupied housing units"), column_title, ""),
    income = if_else(str_detect(column_title, "\\$"), column_title, ""),
    cost_burdened = if_else(str_detect(column_title, "30 percent or more"), "Housing cost burden", "No housing cost burden"),
    .after = column_title
  ) |>
  naniar::replace_with_na(list(tenure = "", income = "")) |>
  tidyr::fill(tenure, income, .direction = "down") |>
  mutate(
    income = str_replace_all(income, ",000|(,999$)", "K"),
    income = forcats::fct_inorder(income),
    income = forcats::fct_relevel("Less than $20K")
  )

recoded_housing_cost_income %>%
  filter(indent == 2) %>%
  select(name, column_title, tenure,
         estimate, moe, perc_estimate, moe_perc) %>%
  filter(!(column_title %in% c("Zero or negative income", "No cash rent"))) %>%
  group_by(name, tenure) %>%
  gt::gt() %>%
  gt::cols_merge_uncert(col_val = "estimate",
                        col_uncert = "moe") %>%
  gt::cols_merge_uncert(col_val = "perc_estimate",
                        col_uncert = "moe_perc") %>%
  gt::fmt_percent(contains("perc"), decimals = 0) %>%
  gt::cols_label(
    column_title = "",
    estimate = "Estimate (MOE)",
    perc_estimate = "% of Total"
  )


recoded_housing_cost_income |>
  filter(indent == 3) %>%
  group_by(
    name, income, cost_burdened
  ) |>
  summarise(
    total_est = sum(estimate, na.rm = TRUE),
    total_perc = sum(perc_estimate)
  ) %>%
  ggplot() +
  geom_col(aes(x = total_perc, y = income, fill = cost_burdened), alpha = 0.8) +
  facet_wrap(~name) +
  scale_x_continuous(labels = scales::label_percent()) +
  plot_theme() +
  pilot::scale_fill_pilot() +
  theme(
    legend.position = "bottom",
    legend.justification = c("right", "bottom")
  ) +
  labs(
    y = "Household income",
    x = "Share of total households",
    fill = "Category"
  )

ggsave(
  filename = glue::glue("{janitor::make_clean_names(params$area_label)}_income_cost_burden_plot.pdf"),
  device = cairo_pdf,
  width = 8.5, height = 6
)

recoded_housing_cost_income |>
  filter(indent == 2) |>
  mutate(
    tenure = str_remove(tenure, " housing units$"),
    income = str_replace_all(income, ",000|(,999$)", "K")
  ) |>
  ggplot() +
  geom_col(aes(x = income, y = perc_estimate, fill = tenure), alpha = 0.85) +
  facet_wrap(~name) +
  scale_y_continuous(labels = scales::label_percent()) +
  coord_flip() +
  plot_theme() +
  pilot::scale_fill_pilot() +
  theme(
    legend.position = "bottom",
    legend.justification = c("left", "bottom")
  ) +
  labs(
    x = "Household income",
    y = "Share of total households",
    fill = "Tenure"
  )

ggsave(
  filename = glue::glue("{janitor::make_clean_names(params$area_label)}_income_tenure_plot.pdf"),
  device = cairo_pdf,
  width = 8.5, height = 6
)

```

